name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Prevent hanging

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "22.12.0"  # Match your local version
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
      env:
        
        MONGODB_URI: ${{ secrets.MONGODB_URI }}  # Ensure this secret is set in your repository settings